### ISSUE TITLE
想美化介面

### ISSUE THREAD

**Issue by jxcodetw** [ncu-weather/ncu-weather-cli#1]
http://ask.xmodulo.com/weather-forecasts-command-line-linux.html

**Comment by lovenery** [comment]
i made a desktop version, so maybe it isn't necessary to do this?
check below url 
[https://ncu-weather.github.io/](https://ncu-weather.github.io/)

**Comment by jxcodetw** [comment]
![](https://cdn.meme.am/cache/instances/folder320/52246320.jpg)
