### ISSUE TITLE
Why? 😁 

### ISSUE THREAD

**Issue by JimLynchCodes** [ncu-weather/ncu-weather-cli#4]
I believe that "ncu" should be the command for "node check updates"...

**Comment by lovenery** [comment]
I notice that the npm-check-updates project is built earlier than this small project, but the author chose "npm-check-updates" as its package name. (the npm-check-updates v1.0.0 was published 6 years ago, and this project was published 2 years ago.)
I do not intentionally occupy the "ncu" package name, and if the authors want the name, I am willing to transfer it.

Hope it works for you.

**Comment by mutantsausagedog** [comment]
I did stare at the screen for some time when I got a weather update and a message to dress warmly instead of the expected package version updates detail :)
